export const hotelTypes = [
    "Budget",
    "Boutique",
    "Luxury",
    "Ski Resort",
    "Business",
    "Family",
    "Romantic",
    "Hiking Resort",
    "Cabin",
    "Beach Resort",
    "Golf Resort",
    "Motel",
    "All Inclusive",
    "Pet Friendly",
    "Self Catering",
  ];
  export const hotelFacilities = [
    "Free WiFi",
    "Parking",
    "Airport Shuttle",
    "Family Rooms",
    "Non-Smoking Rooms",
    "Outdoor Pool",
    "Spa",
    "Fitness Center",
    "Airport Shuttle Service",
    "Pet-Friendly Rooms",
    "Family-Friendly (Kids Stay Free / Kids' Club)",
    "Business Center / Co-working Space",
    "Complimentary Breakfast",
    "Room Service",
    "Laundary Service"

  ];